version: "3.8"

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.0.1
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    command: mlflow ui --host 0.0.0.0

  pipeline:
    build:
      context: .
      dockerfile: src/Dockerfile
    depends_on:
      - mlflow

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
